docusaurus.config.js
package.json
yarn.lock

This PR adds the search functionality to the website using the [docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local) plugin.

feat: add search plugin to docs

---

src/components/Tabs.js
src/pages/index.js

feat(frontend): Rework flow examples

---

docs/openflow.md

Also fix casing for typescript javascript json

more documentation for the suspend option and its behaviour

---

docs/how-tos/0_self_host.md

Updated Helm section with short notes about Enterprise release caching feature.  Not incredibly specific, but more details will be in the helm chart repo, too.

Notes on Enterprise and Helm

---

docs/how-tos/0_self_host.md

Update snippets and instructions for self hosting with Helm section to align with updated helm repo.

Updated helm install in self hosting

---

src/landing/AppSection.jsx
src/landing/FlowSection.jsx
src/landing/ScriptSection.tsx

Adding go-to-app buttons.jsx

---

docs/misc/2_setup_oauth/index.md

added gsheet resource oauth step

added gsheet resource oauth step

---

docs/misc/8_windmill_compared_to_peers/index.md

Also there are a couple words here "blent" and "technicity" which are technically English but very obscure. I'm not clear enough on what the author was actually trying to say in order to replace them.

Fix some typos in the docs

---

docs/advanced/1_self_host/index.md

Clarify new app setup for self hosted instances

feat: Add Instructions for New App Setup

---

docs/misc/9_Guides/AgGrid_Table/index.md

cellEditorParams should take a object, not a function

Fixed aggrid select button example

---

docs/misc/9_Guides/AgGrid_Table/index.md

Turned out to be a bug in windmill and not in my documentation 😎

Revert "Fixed aggrid select button example"

---

docs/advanced/3_cli/sync.md
docs/advanced/3_cli/workspace-management.md
docs/advanced/4_local_development/index.md

1. Clarified workspace addition
2. Added section in local development on Getting started
3. Added a temporary note on sync command about windows

Updated docs to clarify steps for local development.

---

src/landing/AppSection.tsx
src/landing/CoreSection.tsx
src/landing/FlowSection.tsx
src/landing/LandingSectionWrapper.tsx
src/landing/ScriptSection.tsx
src/landing/cards/CardStyles.css
src/landing/cards/Cards.tsx
src/pages/index.js
tailwind.config.js

Core sections

---

docs/advanced/1_self_host/index.md

~~Use -d on all `docker compose up` commands, and include a reminder to restart the containers after pulling the latest images.~~
Related Discord message: https://discord.com/channels/930051556043276338/930051949888405524/1140473986053054474

 Update Self Host to explain --detach and updating

---

src/components/Solutions.tsx
src/pages/solutions/airtable.tsx
src/pages/solutions/hubspot.tsx
src/pages/solutions/supabase.tsx

Made solutions pages responsive

---

docs/advanced/8_preinstall_binaries/index.mdx

added section about playwright and how to use custom docker builds in the docker-compose file

updated docs with playwright and docker compose examples

---

docs/code_editor/add_variables_resources.mdx
docs/code_editor/index.mdx
docs/core_concepts/2_variables_and_secrets/index.mdx
docs/core_concepts/3_resources_and_types/index.mdx
docs/core_concepts/index.mdx
src/landing/ScriptSection.tsx

(sorry for multiple commits; I did this through the GitHub UI)

Remove stray word from several places

---

docs/misc/3_benchmarks/aws_lambda/index.mdx
docs/misc/3_benchmarks/index.mdx
sidebars.js

- Fixed pending broken link on benchmarks
- Order benchmark

broken link benchmark fixed

---

package-lock.json
package.json
src/utils/useInkeepSettings.tsx

**Tabs**
- Add dedicated tabs for 'Docs','Blog', 'API', and 'Home'
- Disabled the 'All' tab
To customize the ordering or display, see searchSettings.tabSettings and baseSettings.breadcrumbRules
**Rendering**
- Made a few improvements to rendering performance.
- added a configurable 'debounceTime' property to searchSettings for additional tuning of the search API submission/re-render

Adding 'API' and 'Blog' tab, making performance improvements to Inkeep Widget

---

docs/integrations/bigquery.mdx
docs/integrations/mssql.md
docs/integrations/mysql.md
docs/integrations/postgresql.md

I promise we're not just going to commit spelling errors!

fix: spelling of databases

---

docs/advanced/1_self_host/index.mdx
package-lock.json

It's fixed for public domains, not for local, and it does not have traefik setup steps (which I can add if wanted) just didn't want to expand the section too much

fixed traefik config

---

docs/misc/4_contributing/index.md
sidebars.js

Added security bounty and fixed language throughout.

Rewrote contributor guide

---

docs/core_concepts/28_agent_workers/index.mdx
docs/core_concepts/29_oidc/index.mdx
docs/core_concepts/index.mdx
sidebars.js
src/components/Pricing.js

- Fix build oidc
- Update enterprise features

fix build oidc

---

docs/advanced/16_external_auth_with_jwt/index.mdx

- **fix: improve JWT external auth groups docs**
- **fix: nit**

feat: add docs for JWKs when using external jwt auth

---

blog/2023-12-27-bash-script-arguments/index.md
blog/2024-04-18-useful-python-scripts/index.md
changelog/2024-01-23-rich-render/index.md
changelog/2024-02-15-ai-copilot/index.md
changelog/2024-02-27-pin-database/index.md
changelog/2024-03-04-workflow-as-code/index.md
changelog/2024-03-13-configurable-languages/index.md
changelog/2024-03-27-map-support-renderer/index.md
changelog/2024-03-27-markdown-support/index.md
changelog/2024-04-24-jobs-labels/index.md
changelog/2024-05-13-nativets-wmill-library/index.md
changelog/2024-05-15-concurrency-limit-observability/index.md
changelog/2024-05-15-php-support/index.md
changelog/2024-06-10-track-relative-imports/index.md
changelog/2024-06-17-oneof-inputs/index.md
changelog/2024-07-26-pre-bundle-bun-scripts/index.md
docs/getting_started/0_scripts_quickstart/1_typescript_quickstart/index.mdx

- **Pre-bundle ts changelog**
- **Doc mention to changelog**

Pre-bundle ts changelog

---

docs/getting_started/0_scripts_quickstart/10_ansible_quickstart/index.mdx

* Ansible vault
* Git repos as dependencies

Update ansible docs with new features

---

src/css/custom.css

Videos get heavily cropped on the top and bottom on wide screens, which is annoying

Fix video cropped in fullscreen

---

docs/misc/2_setup_oauth/index.mdx

- Add Nextcloud to supported SSO providers list
- Add complete setup instructions for Nextcloud OAuth integration
- Include link to official Nextcloud OAuth2 documentation

Add Nextcloud OAuth/SSO documentation
